# .NET Desktop



# Build and run tests for .NET Desktop or Windows classic desktop solutions.
# Add steps that publish symbols, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/apps/windows/dot-net

trigger:
- master

pool:
  vmImage: 'windows-latest'

variables:
  solution: '**/*.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'

steps:
- task: CmdLine@2
  inputs:
    script: 'del /q "C:\Program Files\dotnet\sdk\NuGetFallbackFolder\*"'



- task: ArtifactoryDotnetCore@1
  inputs:
    command: 'restore'
    artifactoryService: 'nuget test'
    targetResolveRepo: 'nuget'
    arguments: '--verbosity detailed -s https://loreny4.jfrog.io/artifactory/api/nuget/nuget -f .'
    rootPath: '**/*.sln'